all: generator std brute checker

generator:generator.cpp
	g++ generator.cpp -o g -std=c++17

std:std.cpp
	g++ std.cpp -o g -std=c++17

brute:brute.cpp
	g++ brute.cpp -o brute -o -std=c++17 -DLOCAL

checker:checker.cpp
	g++ checker.cpp -o checker -std=c++17